force-app/main/default/objects/Book__c/Book__c.object-meta.xml
<CustomObject>
    <description>An object used to store information about a book.</description>
    <label>Book</label>
    <nameField>
        <displayFormat>B-{0000000000}</displayFormat>
        <label>Book Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Books</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Book__c/fields/ISBN__c.field-meta.xml
<CustomField>
    <fullName>ISBN__c</fullName>
    <label>ISBN</label>
    <precision>13</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FavoritedBook__c/FavoritedBook__c.object-meta.xml
<CustomObject>
    <label>FavoritedBook</label>
    <nameField>
        <displayFormat>B-{0000000000}</displayFormat>
        <label>FavoritedBook Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>FavoritedBooks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FavoritedBook__c/fields/Book__c.field-meta.xml
<CustomField>
    <fullName>Book__c</fullName>
    <label>Book</label>
    <referenceTo>Book__c</referenceTo>
    <relationshipLabel>FavoritedBooks</relationshipLabel>
    <relationshipName>FavoritedBooks</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/FavoritedBook__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>FavoritedBooks</relationshipLabel>
    <relationshipName>FavoritedBooks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/FavoriteBook.cls
public without sharing class FavoriteBook {

    @AuraEnabled
    public static List<Book__c> getFavoriteBooks() {
        String currentUserId = UserInfo.getUserId();
        User currentUser = [SELECT Id, ContactId FROM User WHERE Id=:currentUserId];
        List<FavoritedBook__c> favoritedBookList = [SELECT Book__c FROM FavoritedBook__c WHERE (Contact__c = :currentUser.ContactId)];
        List<String> favoritedBookIds = new List<String>();
        for (FavoritedBook__c favBook : favoritedBookList) {
            favoritedBookIds.add(favBook.Book__c);
        }
        List<Book__c> favoriteBookList = [SELECT Id FROM Book__c WHERE (Id IN :favoritedBookIds)];
        return favoriteBookList;
    }
    
    @AuraEnabled
    public static void addToFavorites(Book__c bookToFavorite) {
        Decimal bookISBN = bookToFavorite.ISBN__c;
		List<Book__c> favoriteBookList = getFavoriteBooks();
        
        // Check to see if the book is already favorited
        for (Book__c favBook : favoriteBookList) {
            if (favBook.ISBN__c == bookISBN) {
                System.debug('This book is already favorited.');
                return;
            }
        }        

        // If it isn't, create a new FavoriteBook record
        String currentUserId = UserInfo.getUserId();
        User currentUser = [SELECT Id, ContactId FROM User WHERE Id=:currentUserId];
        List<Book__c> currentBook = [SELECT Id FROM Book__c WHERE (ISBN__c=:bookISBN)];
        
        // Create a new book record
        insert bookToFavorite;
        
        // 
		FavoritedBook__c newFavoriteBook = new FavoritedBook__c(Contact__c = currentUser.ContactId, Book__c = bookToFavorite.Id);
        insert newFavoriteBook;
        
    }
    
}